name: ci

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags: ["*"]

jobs:
  go-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
      with:
        go-version-file: 'go.mod'
    - run: go test -v ./...
